# .goreleaser.yml
# Build customization

project_name: terraform-provider-gocd

builds:
  - binary: terraform-provider-gocd
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - name_template: "terraform-provider-gocd-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

brews:
  - github:
      owner: beamly
      name: homebrew-tap
    homepage: https://github.com/beamly/terraform-provider-gocd
    description: Terraform Provider for ThoughtWorks GoCD
    dependencies:
      - terraform
      - drewsonne/homebrew-tap/tf-install-provider
    caveats: |
      After installing, you will need to copy the provider to a place terraform can find it by running:
        tf-install-provider artifactory
    test: |
      system "#{bin}/terraform-provider-gocd; [[ $? -eq 1 ]]"
