language: go
go:
  - 1.10.x
  - 1.11.x


services:
  - docker

addons:
  apt:
    packages:
    - rpm

matrix:
  fast_finish: true
  allow_failures:
    - go: 1.11.x

env:
  matrix:
    - GOCD_URL=http://127.0.0.1:8153/go/
    - GOCD_URL=https://127.0.0.1:8154/go/ GOCD_SKIP_SSL_CHECK=1

cache:
  pip: true

before_install:
  - openssl aes-256-cbc -K $encrypted_b7c1913c3ccb_key -iv $encrypted_b7c1913c3ccb_iv -in .gitcookies.enc -out $HOME/.gitcookies -d
  - make before_install

script:
  - make vet
  - make script

after_failure:
  - make after_failure

after_success:
  - make after_success

deploy:
  # We do a `skip_cleanup` because when the docker-compose runs, it creates files in the host file system with the
  # userid `1000`. Our travis user does not have the userid `1000`, so it can not clean those files up, causing the
  # deploy to break. We do a `git clean` from the Makefile to perform necessary cleanup.
  - provider: script
    skip_cleanup: true
    script: make deploy_on_tag
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.10\.([0-9]+|x)?$ && $GOCD_SKIP_SSL_CHECK = 1
  - provider: script
    skip_cleanup: true
    script: make deploy_on_develop
    on:
      branch: develop
